#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("com.wandio.Resource", IsApplication=false)]

namespace com.wandio
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public static int fnmContentPadding = 2130771975;
			
			// aapt resource value: 0x7f010001
			public static int fnmMargin = 2130771969;
			
			// aapt resource value: 0x7f010005
			public static int fnmMarginBottom = 2130771973;
			
			// aapt resource value: 0x7f010004
			public static int fnmMarginLeft = 2130771972;
			
			// aapt resource value: 0x7f010003
			public static int fnmMarginRight = 2130771971;
			
			// aapt resource value: 0x7f010002
			public static int fnmMarginTop = 2130771970;
			
			// aapt resource value: 0x7f010008
			public static int fnmPadding = 2130771976;
			
			// aapt resource value: 0x7f01000c
			public static int fnmPaddingBottom = 2130771980;
			
			// aapt resource value: 0x7f01000a
			public static int fnmPaddingLeft = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public static int fnmPaddingRight = 2130771979;
			
			// aapt resource value: 0x7f010009
			public static int fnmPaddingTop = 2130771977;
			
			// aapt resource value: 0x7f010006
			public static int fnmTabBackground = 2130771974;
			
			// aapt resource value: 0x7f01000d
			public static int fnmTextAlpha = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public static int fnmTextStyle = 2130771982;
			
			// aapt resource value: 0x7f010000
			public static int fnmUnderlineColor = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030000
			public static int bold = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int italic = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int normal = 2130903042;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020000
			public static int library_name = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ForwardNavigationMenu = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 7
			public static int ForwardNavigationMenu_fnmContentPadding = 7;
			
			// aapt resource value: 1
			public static int ForwardNavigationMenu_fnmMargin = 1;
			
			// aapt resource value: 5
			public static int ForwardNavigationMenu_fnmMarginBottom = 5;
			
			// aapt resource value: 4
			public static int ForwardNavigationMenu_fnmMarginLeft = 4;
			
			// aapt resource value: 3
			public static int ForwardNavigationMenu_fnmMarginRight = 3;
			
			// aapt resource value: 2
			public static int ForwardNavigationMenu_fnmMarginTop = 2;
			
			// aapt resource value: 8
			public static int ForwardNavigationMenu_fnmPadding = 8;
			
			// aapt resource value: 12
			public static int ForwardNavigationMenu_fnmPaddingBottom = 12;
			
			// aapt resource value: 10
			public static int ForwardNavigationMenu_fnmPaddingLeft = 10;
			
			// aapt resource value: 11
			public static int ForwardNavigationMenu_fnmPaddingRight = 11;
			
			// aapt resource value: 9
			public static int ForwardNavigationMenu_fnmPaddingTop = 9;
			
			// aapt resource value: 6
			public static int ForwardNavigationMenu_fnmTabBackground = 6;
			
			// aapt resource value: 13
			public static int ForwardNavigationMenu_fnmTextAlpha = 13;
			
			// aapt resource value: 14
			public static int ForwardNavigationMenu_fnmTextStyle = 14;
			
			// aapt resource value: 0
			public static int ForwardNavigationMenu_fnmUnderlineColor = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
