#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MyApp.Resource", IsApplication=true)]

namespace MyApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.wandio.Resource.Attribute.fnmContentPadding = global::MyApp.Resource.Attribute.fnmContentPadding;
			global::com.wandio.Resource.Attribute.fnmMargin = global::MyApp.Resource.Attribute.fnmMargin;
			global::com.wandio.Resource.Attribute.fnmMarginBottom = global::MyApp.Resource.Attribute.fnmMarginBottom;
			global::com.wandio.Resource.Attribute.fnmMarginLeft = global::MyApp.Resource.Attribute.fnmMarginLeft;
			global::com.wandio.Resource.Attribute.fnmMarginRight = global::MyApp.Resource.Attribute.fnmMarginRight;
			global::com.wandio.Resource.Attribute.fnmMarginTop = global::MyApp.Resource.Attribute.fnmMarginTop;
			global::com.wandio.Resource.Attribute.fnmPadding = global::MyApp.Resource.Attribute.fnmPadding;
			global::com.wandio.Resource.Attribute.fnmPaddingBottom = global::MyApp.Resource.Attribute.fnmPaddingBottom;
			global::com.wandio.Resource.Attribute.fnmPaddingLeft = global::MyApp.Resource.Attribute.fnmPaddingLeft;
			global::com.wandio.Resource.Attribute.fnmPaddingRight = global::MyApp.Resource.Attribute.fnmPaddingRight;
			global::com.wandio.Resource.Attribute.fnmPaddingTop = global::MyApp.Resource.Attribute.fnmPaddingTop;
			global::com.wandio.Resource.Attribute.fnmTabBackground = global::MyApp.Resource.Attribute.fnmTabBackground;
			global::com.wandio.Resource.Attribute.fnmTextAlpha = global::MyApp.Resource.Attribute.fnmTextAlpha;
			global::com.wandio.Resource.Attribute.fnmTextStyle = global::MyApp.Resource.Attribute.fnmTextStyle;
			global::com.wandio.Resource.Attribute.fnmUnderlineColor = global::MyApp.Resource.Attribute.fnmUnderlineColor;
			global::com.wandio.Resource.Id.bold = global::MyApp.Resource.Id.bold;
			global::com.wandio.Resource.Id.italic = global::MyApp.Resource.Id.italic;
			global::com.wandio.Resource.Id.normal = global::MyApp.Resource.Id.normal;
			global::com.wandio.Resource.String.library_name = global::MyApp.Resource.String.library_name;
			global::com.wandio.Resource.Styleable.ForwardNavigationMenu = global::MyApp.Resource.Styleable.ForwardNavigationMenu;
			global::com.wandio.Resource.Styleable.ForwardNavigationMenu_fnmContentPadding = global::MyApp.Resource.Styleable.ForwardNavigationMenu_fnmContentPadding;
			global::com.wandio.Resource.Styleable.ForwardNavigationMenu_fnmMargin = global::MyApp.Resource.Styleable.ForwardNavigationMenu_fnmMargin;
			global::com.wandio.Resource.Styleable.ForwardNavigationMenu_fnmMarginBottom = global::MyApp.Resource.Styleable.ForwardNavigationMenu_fnmMarginBottom;
			global::com.wandio.Resource.Styleable.ForwardNavigationMenu_fnmMarginLeft = global::MyApp.Resource.Styleable.ForwardNavigationMenu_fnmMarginLeft;
			global::com.wandio.Resource.Styleable.ForwardNavigationMenu_fnmMarginRight = global::MyApp.Resource.Styleable.ForwardNavigationMenu_fnmMarginRight;
			global::com.wandio.Resource.Styleable.ForwardNavigationMenu_fnmMarginTop = global::MyApp.Resource.Styleable.ForwardNavigationMenu_fnmMarginTop;
			global::com.wandio.Resource.Styleable.ForwardNavigationMenu_fnmPadding = global::MyApp.Resource.Styleable.ForwardNavigationMenu_fnmPadding;
			global::com.wandio.Resource.Styleable.ForwardNavigationMenu_fnmPaddingBottom = global::MyApp.Resource.Styleable.ForwardNavigationMenu_fnmPaddingBottom;
			global::com.wandio.Resource.Styleable.ForwardNavigationMenu_fnmPaddingLeft = global::MyApp.Resource.Styleable.ForwardNavigationMenu_fnmPaddingLeft;
			global::com.wandio.Resource.Styleable.ForwardNavigationMenu_fnmPaddingRight = global::MyApp.Resource.Styleable.ForwardNavigationMenu_fnmPaddingRight;
			global::com.wandio.Resource.Styleable.ForwardNavigationMenu_fnmPaddingTop = global::MyApp.Resource.Styleable.ForwardNavigationMenu_fnmPaddingTop;
			global::com.wandio.Resource.Styleable.ForwardNavigationMenu_fnmTabBackground = global::MyApp.Resource.Styleable.ForwardNavigationMenu_fnmTabBackground;
			global::com.wandio.Resource.Styleable.ForwardNavigationMenu_fnmTextAlpha = global::MyApp.Resource.Styleable.ForwardNavigationMenu_fnmTextAlpha;
			global::com.wandio.Resource.Styleable.ForwardNavigationMenu_fnmTextStyle = global::MyApp.Resource.Styleable.ForwardNavigationMenu_fnmTextStyle;
			global::com.wandio.Resource.Styleable.ForwardNavigationMenu_fnmUnderlineColor = global::MyApp.Resource.Styleable.ForwardNavigationMenu_fnmUnderlineColor;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int fnmContentPadding = 2130771975;
			
			// aapt resource value: 0x7f010001
			public const int fnmMargin = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int fnmMarginBottom = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int fnmMarginLeft = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int fnmMarginRight = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int fnmMarginTop = 2130771970;
			
			// aapt resource value: 0x7f010008
			public const int fnmPadding = 2130771976;
			
			// aapt resource value: 0x7f01000c
			public const int fnmPaddingBottom = 2130771980;
			
			// aapt resource value: 0x7f01000a
			public const int fnmPaddingLeft = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int fnmPaddingRight = 2130771979;
			
			// aapt resource value: 0x7f010009
			public const int fnmPaddingTop = 2130771977;
			
			// aapt resource value: 0x7f010006
			public const int fnmTabBackground = 2130771974;
			
			// aapt resource value: 0x7f01000d
			public const int fnmTextAlpha = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int fnmTextStyle = 2130771982;
			
			// aapt resource value: 0x7f010000
			public const int fnmUnderlineColor = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int TextColor = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fav = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int itembg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int note = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int pin = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int speed = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int bold = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int italic = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int menu = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int normal = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ContentView = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int fav = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int note = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int places = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int speed = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ForwardNavigationMenu = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 7
			public const int ForwardNavigationMenu_fnmContentPadding = 7;
			
			// aapt resource value: 1
			public const int ForwardNavigationMenu_fnmMargin = 1;
			
			// aapt resource value: 5
			public const int ForwardNavigationMenu_fnmMarginBottom = 5;
			
			// aapt resource value: 4
			public const int ForwardNavigationMenu_fnmMarginLeft = 4;
			
			// aapt resource value: 3
			public const int ForwardNavigationMenu_fnmMarginRight = 3;
			
			// aapt resource value: 2
			public const int ForwardNavigationMenu_fnmMarginTop = 2;
			
			// aapt resource value: 8
			public const int ForwardNavigationMenu_fnmPadding = 8;
			
			// aapt resource value: 12
			public const int ForwardNavigationMenu_fnmPaddingBottom = 12;
			
			// aapt resource value: 10
			public const int ForwardNavigationMenu_fnmPaddingLeft = 10;
			
			// aapt resource value: 11
			public const int ForwardNavigationMenu_fnmPaddingRight = 11;
			
			// aapt resource value: 9
			public const int ForwardNavigationMenu_fnmPaddingTop = 9;
			
			// aapt resource value: 6
			public const int ForwardNavigationMenu_fnmTabBackground = 6;
			
			// aapt resource value: 13
			public const int ForwardNavigationMenu_fnmTextAlpha = 13;
			
			// aapt resource value: 14
			public const int ForwardNavigationMenu_fnmTextStyle = 14;
			
			// aapt resource value: 0
			public const int ForwardNavigationMenu_fnmUnderlineColor = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
